# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('ModifiedTime', models.DateTimeField(auto_now=True)),
                ('BGGRef', models.URLField(blank=True, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('UPC', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('ModifiedTime', models.DateTimeField(auto_now=True)),
                ('RFIDTag', models.BigIntegerField(blank=True, null=True)),
                ('PreWeight', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('RegisteredPersonalGame', models.BooleanField(default=False)),
                ('Boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('ModifiedTime', models.DateTimeField(auto_now=True)),
                ('BadgeNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('IsBusiness', models.BooleanField(default=False)),
                ('Suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=2, null=True)),
                ('Zip', models.CharField(blank=True, max_length=5, null=True)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('ReceiveNewsletter', models.BooleanField(default=False)),
                ('NewsletterFrequencyCode', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.Person'),
        ),
    ]
