# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-25 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0002_auto_20180525_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='CheckedInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='PostConditionNote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='PreConditionNote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
