# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0005_auto_20180531_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['LastName', 'FirstName']},
        ),
    ]
