# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0006_auto_20180606_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('BadgeNumber',)]),
        ),
    ]
