# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0007_auto_20180606_1718'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['LastName', 'FirstName'], name='Collections_LastNam_0e6bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['BadgeNumber'], name='Collections_BadgeNu_8f1ad2_idx'),
        ),
    ]
