# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0008_auto_20180606_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['Name']},
        ),
        migrations.AlterUniqueTogether(
            name='boardgame',
            unique_together=set([('Name', 'BGGRef')]),
        ),
    ]
