# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0009_auto_20180606_1732'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['Name', 'BGGRef'], name='Collections_Name_2bedc3_idx'),
        ),
    ]
