# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0010_auto_20180606_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['Boardgame', 'Person']},
        ),
    ]
