# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0011_auto_20180606_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-CheckedInTime', 'CheckedOutTime']},
        ),
    ]
