# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0012_auto_20180606_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='CheckedOutBy',
        ),
    ]
