# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0013_remove_checkout_checkedoutby'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='Shelved',
            field=models.BooleanField(default=False),
        ),
    ]
