# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0014_collection_shelved'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['CheckedOutTime', 'CheckedInTime'], name='Collections_Checked_559462_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['BoardgameFromCollection'], name='Collections_Boardga_5fbfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['Boardgame'], name='Collections_Boardga_915b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['Person'], name='Collections_Person__9bfd33_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['Shelved'], name='Collections_Shelved_9c55d9_idx'),
        ),
    ]
